### ISSUE TITLE
substituir phpqatools do Pear para instalação via Composer

### ISSUE THREAD

**Issue by renanbr** [wendtecnologia/was4p#14]
pear.phpqatools.org está descontinuado
http://pear.phpqatools.org

a tarefa realizada no arquivo https://github.com/wendtecnologia/was4p/blob/master/scripts/05-qatools.sh deve ser atualizada

uma alternativa possível é a instalação pelo Composer
https://getcomposer.org/doc/03-cli.md#global

**Comment by walkeralencar** [comment]
Eu percebi isso na sexta(25/04) quando estava instalando um novo server  com ZS 6.3 e php 5.5;

Já estou trabalhando para buscar uma solução...  mas ainda nao tinha encontrado esse ponto, vou fazer umas simulações para ver o comportamento... ;)
