### ISSUE TITLE
Script de jenkins + Plugins

### ISSUE THREAD

**Issue by walkeralencar** [wendtecnologia/was4p#3]
Criar e publicar o script de instalação do jenkins + plugins para integração com o phpQaTools e o PHPTemplate já pré-configurado.

**Comment by renanbr** [comment]
@walkeralencar a máquina virtual é para desenvolvimento em PHP ou é um servidor de integração contínua? ou é as duas coisas ao mesmo tempo?

**Comment by walkeralencar** [comment]
@renanbr a idéia é fornecer os scripts prontos para quem montar ter a flexibilidade de fazer o que achar melhor conforme suas necessidades

Vou disponibilzar as máquinas prontas com 3 versões:
Minimal: ZendServer+Git
Default: ZendServer+Git+PHPQaTools
Full: ZendServer+Git+PHPQaTools+Jenkins+PHPTemplate

Quem quiser banco de dados que instale por conta própria, mas claro, a idéia é ter o script tb.
