### ISSUE TITLE
Adicionar instalação de IDE

### ISSUE THREAD

**Issue by renanbr** [wendtecnologia/was4p#7]
Instalar IDE com os seguintes features:
- Controle de Versão (git, hg, svn)
- Composer
- Debug

**Comment by walkeralencar** [comment]
@renanbr não entendi essa parte, atualmente estou montando ubuntu server, mas funciona do mesmo jeito para o ubuntu desktop.

Tenho que checar, mas se nao me engano, o Zend Server 6 já vem com o Composer e com o Zend Debugger( q é incompativel com o xDebug, mas já resolvi esse problema) o git tb já deixei instalado de inicio, SVN é opcional...

Mas seria interessante uma documentação sobre isso. :)

**Comment by renanbr** [comment]
@walkeralencar não havia percebido que a idéia era essa, pensei que era um ambiente que iria incluir interface visual e tudo mais... acho que esse issue pode ser fechado
